### PR TITLE
fix(build): type definitions, esbuild + esm, package exports

### PR DESCRIPTION
**Pull request by mloenow**
Fixes issue with missing type definitions (related: https://github.com/a-rothwell/rivet-plugin-mongodb/issues/2#issuecomment-1879460809) and correctly bundles both ESM and CommonJS. This should make development from TypeScript functional 😬 

- [ ] There's a problem I'm facing, though: 

  ```
  Installing plugin: rivet-plugin-mongodb...
  Checking for plugin updates: rivet-plugin-mongodb@main
  Plugin is a git repository, skipping reinstall: rivet-plugin-mongodb@main
  
  Error installing plugin: path: /Users/ml/Library/Application Support/com.ironcladapp.rivet/plugins/rivet-plugin-mongodb-main/package/./dist/cjs/index.js: No such file or directory (os error 2)
  ```
  
  This happens because the export paths are required to begin with a dot. I've opened an issue in the main Rivet repository: https://github.com/Ironclad/rivet/issues/303

I'm not sure you want the built files as part of this commit or when you bump your version, but I can remove them if needed.

Let me know if you think and if you have any feedback 🙂

### CODE REVIEW

**Comment by a-rothwell** [comment]
I think this plugins package.json is missing the following, causing Rivet to attempt to built it during install. Rivet shouldn't need to build it since we build on publish.

```
  "files": [
    "dist"
  ],
  "rivet": {
    "skipInstall": true
  }
```

I can add those real quick and publish V0.0.4.

If that fixes the error you're getting we can go ahead and update this PR to only fix the types

**Comment by mloenow** [comment]
Oh, I should give that a try here as well. Will report back...

**Comment by a-rothwell** [comment]
Install via UI worked for me on a fresh install of the rivet binaries, going to run through some regression testing now

**Comment by a-rothwell** [comment]
I was able to successfully run all the cookbook examples in a new project with the plugin downloaded via the UI.

So if you encounter the same success, we can update this PR to just add the types and I can publish a V0.0.5!

**Comment by mloenow** [comment]
I'm getting some errors now for some reason. Will continue tomorrow 🙂

**Comment by mloenow** [comment]
I found the issue I had. Turns out Rivet wants the plugin to be in ESM and not CommonJS, which I had updated the `main` field in `package.json` to. Fixed now 😄 

I see the example plugin for Rivet does not have CommonJS support - do you want to keep this? If so, do you have an existing CommonJS project you can test this branch on? Otherwise I can remove it an clean up a bit.

**Comment by a-rothwell** [comment]
Thanks! I'm not sure if we need to include the commonJS, let's ask Andy. The docs only mention that [ESM is required for rivet](https://github.com/abrenneke/rivet-plugin-example?tab=readme-ov-file#making-your-own-plugin)

It does appear that most plugins only include ESM, although some plugins like the python-example-plugin include both.

This plugin uses the same bundle.ts that the python-example-plugin originally had.

@abrenneke What are the best practices here?

Possible future work:
It might make sense to create a npx command to bundle plugins in line with the best practices.

**Comment by a-rothwell** [comment]
With the addition of the skipInstall option in the package.json I think we're good to resolve this PR with one of the following actions:

1. Update the PR to only add the type generation to tsconfig
Or
2. Close the PR as the fix to the original issue has been released with V4

Given that skipInstall is now the default with rivet, I will also add the dist folder to the .gitignore.
End users should now get the built bundle from npm that is created at publish.
Developers will need to build locally regardless when they make changes

**Pull request closed without merging**
